/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    categories: Category;
    media: Media;
    articles: Article;
    vegetables: Vegetable;
    'box-notifications': BoxNotification;
    addresses: Address;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      orders: 'orders';
      cart: 'carts';
      addresses: 'addresses';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    vegetables: VegetablesSelect<false> | VegetablesSelect<true>;
    'box-notifications': BoxNotificationsSelect<false> | BoxNotificationsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'faq-page': FaqPage;
    'home-page': HomePage;
    'about-page': AboutPage;
    'products-page': ProductsPage;
    'did-you-know-page': DidYouKnowPage;
    'pickup-point-page': PickupPointPage;
    'contact-page': ContactPage;
    'support-page': SupportPage;
    'checkout-settings': CheckoutSetting;
    'delivery-pickup-configuration': DeliveryPickupConfiguration;
    'mail-settings': MailSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'faq-page': FaqPageSelect<false> | FaqPageSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'products-page': ProductsPageSelect<false> | ProductsPageSelect<true>;
    'did-you-know-page': DidYouKnowPageSelect<false> | DidYouKnowPageSelect<true>;
    'pickup-point-page': PickupPointPageSelect<false> | PickupPointPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'support-page': SupportPageSelect<false> | SupportPageSelect<true>;
    'checkout-settings': CheckoutSettingsSelect<false> | CheckoutSettingsSelect<true>;
    'delivery-pickup-configuration': DeliveryPickupConfigurationSelect<false> | DeliveryPickupConfigurationSelect<true>;
    'mail-settings': MailSettingsSelect<false> | MailSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('admin' | 'customer')[] | null;
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?: {
    docs?: (number | Cart)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (number | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (number | null) | User;
  customerEmail?: string | null;
  transactions?: (number | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'RON' | null;
  accessToken?: string | null;
  shouldBeDeliveredOn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  possibleVegetables: (number | Vegetable)[];
  inventory: number;
  /**
   * The price of the item in RON using 2 decimal points
   */
  price: string;
  hasDiscount?: boolean | null;
  /**
   * The discounted price of the item in RON using 2 decimal points
   */
  discountedPrice?: string | null;
  availableFrom: string;
  availableUntil: string;
  /**
   * Hides the product from the client
   */
  hideProduct: boolean;
  /**
   * Disables the product while still showing it for the clients. If checked, availability dates will be completely ignored. Hide product still works as usual
   */
  disableProduct: boolean;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vegetables".
 */
export interface Vegetable {
  id: number;
  name: string;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: 'netopia' | null;
  netopia?: {
    ntpID?: string | null;
    tempOrderID?: string | null;
    fulfillmentMethod?: ('delivery' | 'pickup') | null;
    shippingAddress?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    shouldBeDeliveredOn?: string | null;
  };
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | User;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  cart?: (number | null) | Cart;
  amount?: number | null;
  currency?: 'RON' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (number | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'RON' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer?: (number | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  mapboxVerified?: boolean | null;
  mapboxPlaceID?: string | null;
  mapboxFullAddress?: string | null;
  mapboxLatitude?: number | null;
  mapboxLongitude?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  publishedOn?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  publishedOn?: string | null;
  description: string;
  thumbnail: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedArticles?: (number | Article)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "box-notifications".
 */
export interface BoxNotification {
  id: number;
  user: number | User;
  box: number | Product;
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'vegetables';
        value: number | Vegetable;
      } | null)
    | ({
        relationTo: 'box-notifications';
        value: number | BoxNotification;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  orders?: T;
  cart?: T;
  addresses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  description?: T;
  thumbnail?: T;
  content?: T;
  relatedArticles?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vegetables_select".
 */
export interface VegetablesSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "box-notifications_select".
 */
export interface BoxNotificationsSelect<T extends boolean = true> {
  user?: T;
  box?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  mapboxVerified?: T;
  mapboxPlaceID?: T;
  mapboxFullAddress?: T;
  mapboxLatitude?: T;
  mapboxLongitude?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  possibleVegetables?: T;
  inventory?: T;
  price?: T;
  hasDiscount?: T;
  discountedPrice?: T;
  availableFrom?: T;
  availableUntil?: T;
  hideProduct?: T;
  disableProduct?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  accessToken?: T;
  shouldBeDeliveredOn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  paymentMethod?: T;
  netopia?:
    | T
    | {
        ntpID?: T;
        tempOrderID?: T;
        fulfillmentMethod?: T;
        shippingAddress?: T;
        shouldBeDeliveredOn?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  headerImage?: (number | null) | Media;
  links: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  slogan: string;
  footerImage?: (number | null) | Media;
  social: {
    facebookUrl: string;
    instagramUrl: string;
  };
  columns: {
    title: string;
    links: {
      label: string;
      url: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page".
 */
export interface FaqPage {
  id: number;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  items: {
    question: string;
    answer: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroBackgroundImage: number | Media;
  /**
   * The title to be used on the hero image
   */
  heroTitle: string;
  /**
   * The subtitle to be used on the hero image
   */
  subtitle: string;
  /**
   * The text to appear on the call to action button
   */
  callToActionText: string;
  /**
   * The title to be used for the highlighted box section within home
   */
  highlightBoxTitle: string;
  /**
   * The content to be used for the highlighted box section within home
   */
  highlightBoxContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * The box to be displayed on home
   */
  featuredProduct?: (number | null) | Product;
  /**
   * The title to be used for the highlighted articles section within home
   */
  highlightArticlesTitle: string;
  /**
   * The content to be used for the highlighted articles section within home
   */
  highlightArticlesContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * The articles to be displayed on home
   */
  highlightedArticles?: (number | Article)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  teamImage: number | Media;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  members: {
    photo: number | Media;
    name: string;
    bio: string;
    id?: string | null;
  }[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page".
 */
export interface ProductsPage {
  id: number;
  /**
   * The title to be used for the boxes section
   */
  boxesSectionTitle: string;
  /**
   * The content to be used for the boxes section
   */
  boxesSectionContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * The title to be used for the how it works section
   */
  howItWorksTitle: string;
  /**
   * The content to be used for the how it works section
   */
  howItWorksContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  step1: {
    title: string;
    description: string;
  };
  step2: {
    title: string;
    description: string;
  };
  step3: {
    title: string;
    description: string;
  };
  /**
   * The title to be used for the What's In Your Box section
   */
  whatsInYourBoxTitle: string;
  /**
   * The content to be used for the What's In Your Box section
   */
  whatsInYourBoxContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "did-you-know-page".
 */
export interface DidYouKnowPage {
  id: number;
  title: string;
  /**
   * The content to be used for the did you know page
   */
  didYouKnowContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pickup-point-page".
 */
export interface PickupPointPage {
  id: number;
  heroImage?: (number | null) | Media;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  locationTitle: string;
  locationLine1: string;
  locationLine2: string;
  openingHoursTitle: string;
  openingHours: {
    day: string;
    hours: string;
    id?: string | null;
  }[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  phoneLabel?: string | null;
  phone: string;
  emailLabel?: string | null;
  email: string;
  whatsappLabel?: string | null;
  whatsappNumber: string;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-page".
 */
export interface SupportPage {
  id: number;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  phoneLabel: string;
  phone: string;
  emailLabel: string;
  email: string;
  whatsappLabel: string;
  whatsappNumber: string;
  whatsappPrefillMessage: string;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkout-settings".
 */
export interface CheckoutSetting {
  id: number;
  /**
   * The price for delivery in RON using 2 decimal points
   */
  deliveryPrice: string;
  /**
   * The minimum product subtotal required for delivery in RON using 2 decimal points
   */
  minimumDeliveryOrderAmount: string;
  addressDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-pickup-configuration".
 */
export interface DeliveryPickupConfiguration {
  id: number;
  monday?: boolean | null;
  tuesday?: boolean | null;
  wednesday?: boolean | null;
  thursday?: boolean | null;
  friday?: boolean | null;
  saturday?: boolean | null;
  sunday?: boolean | null;
  /**
   * Modify only specific weeks. An empty selected week means no delivery / pickup dates that week.
   */
  weekOverrides?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure transactional order emails. Templates support HTML bodies and {{param}} placeholders. Available params: {{orderID}}, {{orderDate}}, {{deliveryDate}}, {{status}}, {{total}}, {{currency}}, {{customerEmail}}, {{orderURL}}, {{fulfillmentMethod}}, {{fulfillmentLabel}}, {{billingAddress}}, {{shippingAddress}}, {{itemsText}}, {{itemsHTML}}, {{itemsTable}}, {{boxName}}, {{boxURL}}, {{availableFrom}}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail-settings".
 */
export interface MailSetting {
  id: number;
  orderPlaced: {
    /**
     * Use HTML in the body. Inject order values using double curly braces. Available params: {{orderID}}, {{orderDate}}, {{deliveryDate}}, {{status}}, {{total}}, {{currency}}, {{customerEmail}}, {{orderURL}}, {{fulfillmentMethod}}, {{fulfillmentLabel}}, {{billingAddress}}, {{shippingAddress}}, {{itemsText}}, {{itemsHTML}}, {{itemsTable}}, {{boxName}}, {{boxURL}}, {{availableFrom}}
     */
    subject: string;
    /**
     * Use HTML in the body. Inject order values using double curly braces. Available params: {{orderID}}, {{orderDate}}, {{deliveryDate}}, {{status}}, {{total}}, {{currency}}, {{customerEmail}}, {{orderURL}}, {{fulfillmentMethod}}, {{fulfillmentLabel}}, {{billingAddress}}, {{shippingAddress}}, {{itemsText}}, {{itemsHTML}}, {{itemsTable}}, {{boxName}}, {{boxURL}}, {{availableFrom}}
     */
    body: string;
  };
  orderCancelled: {
    /**
     * Use HTML in the body. Inject order values using double curly braces. Available params: {{orderID}}, {{orderDate}}, {{deliveryDate}}, {{status}}, {{total}}, {{currency}}, {{customerEmail}}, {{orderURL}}, {{fulfillmentMethod}}, {{fulfillmentLabel}}, {{billingAddress}}, {{shippingAddress}}, {{itemsText}}, {{itemsHTML}}, {{itemsTable}}, {{boxName}}, {{boxURL}}, {{availableFrom}}
     */
    subject: string;
    /**
     * Use HTML in the body. Inject order values using double curly braces. Available params: {{orderID}}, {{orderDate}}, {{deliveryDate}}, {{status}}, {{total}}, {{currency}}, {{customerEmail}}, {{orderURL}}, {{fulfillmentMethod}}, {{fulfillmentLabel}}, {{billingAddress}}, {{shippingAddress}}, {{itemsText}}, {{itemsHTML}}, {{itemsTable}}, {{boxName}}, {{boxURL}}, {{availableFrom}}
     */
    body: string;
  };
  orderDelivered: {
    /**
     * Use HTML in the body. Inject order values using double curly braces. Available params: {{orderID}}, {{orderDate}}, {{deliveryDate}}, {{status}}, {{total}}, {{currency}}, {{customerEmail}}, {{orderURL}}, {{fulfillmentMethod}}, {{fulfillmentLabel}}, {{billingAddress}}, {{shippingAddress}}, {{itemsText}}, {{itemsHTML}}, {{itemsTable}}, {{boxName}}, {{boxURL}}, {{availableFrom}}
     */
    subject: string;
    /**
     * Use HTML in the body. Inject order values using double curly braces. Available params: {{orderID}}, {{orderDate}}, {{deliveryDate}}, {{status}}, {{total}}, {{currency}}, {{customerEmail}}, {{orderURL}}, {{fulfillmentMethod}}, {{fulfillmentLabel}}, {{billingAddress}}, {{shippingAddress}}, {{itemsText}}, {{itemsHTML}}, {{itemsTable}}, {{boxName}}, {{boxURL}}, {{availableFrom}}
     */
    body: string;
  };
  orderPickedUp: {
    /**
     * Use HTML in the body. Inject order values using double curly braces. Available params: {{orderID}}, {{orderDate}}, {{deliveryDate}}, {{status}}, {{total}}, {{currency}}, {{customerEmail}}, {{orderURL}}, {{fulfillmentMethod}}, {{fulfillmentLabel}}, {{billingAddress}}, {{shippingAddress}}, {{itemsText}}, {{itemsHTML}}, {{itemsTable}}, {{boxName}}, {{boxURL}}, {{availableFrom}}
     */
    subject: string;
    /**
     * Use HTML in the body. Inject order values using double curly braces. Available params: {{orderID}}, {{orderDate}}, {{deliveryDate}}, {{status}}, {{total}}, {{currency}}, {{customerEmail}}, {{orderURL}}, {{fulfillmentMethod}}, {{fulfillmentLabel}}, {{billingAddress}}, {{shippingAddress}}, {{itemsText}}, {{itemsHTML}}, {{itemsTable}}, {{boxName}}, {{boxURL}}, {{availableFrom}}
     */
    body: string;
  };
  boxAvailable: {
    /**
     * Use HTML in the body. Inject order values using double curly braces. Available params: {{orderID}}, {{orderDate}}, {{deliveryDate}}, {{status}}, {{total}}, {{currency}}, {{customerEmail}}, {{orderURL}}, {{fulfillmentMethod}}, {{fulfillmentLabel}}, {{billingAddress}}, {{shippingAddress}}, {{itemsText}}, {{itemsHTML}}, {{itemsTable}}, {{boxName}}, {{boxURL}}, {{availableFrom}}
     */
    subject: string;
    /**
     * Use HTML in the body. Inject order values using double curly braces. Available params: {{orderID}}, {{orderDate}}, {{deliveryDate}}, {{status}}, {{total}}, {{currency}}, {{customerEmail}}, {{orderURL}}, {{fulfillmentMethod}}, {{fulfillmentLabel}}, {{billingAddress}}, {{shippingAddress}}, {{itemsText}}, {{itemsHTML}}, {{itemsTable}}, {{boxName}}, {{boxURL}}, {{availableFrom}}
     */
    body: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  headerImage?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  slogan?: T;
  footerImage?: T;
  social?:
    | T
    | {
        facebookUrl?: T;
        instagramUrl?: T;
      };
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page_select".
 */
export interface FaqPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroBackgroundImage?: T;
  heroTitle?: T;
  subtitle?: T;
  callToActionText?: T;
  highlightBoxTitle?: T;
  highlightBoxContent?: T;
  featuredProduct?: T;
  highlightArticlesTitle?: T;
  highlightArticlesContent?: T;
  highlightedArticles?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  teamImage?: T;
  title?: T;
  description?: T;
  members?:
    | T
    | {
        photo?: T;
        name?: T;
        bio?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page_select".
 */
export interface ProductsPageSelect<T extends boolean = true> {
  boxesSectionTitle?: T;
  boxesSectionContent?: T;
  howItWorksTitle?: T;
  howItWorksContent?: T;
  step1?:
    | T
    | {
        title?: T;
        description?: T;
      };
  step2?:
    | T
    | {
        title?: T;
        description?: T;
      };
  step3?:
    | T
    | {
        title?: T;
        description?: T;
      };
  whatsInYourBoxTitle?: T;
  whatsInYourBoxContent?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "did-you-know-page_select".
 */
export interface DidYouKnowPageSelect<T extends boolean = true> {
  title?: T;
  didYouKnowContent?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pickup-point-page_select".
 */
export interface PickupPointPageSelect<T extends boolean = true> {
  heroImage?: T;
  title?: T;
  description?: T;
  locationTitle?: T;
  locationLine1?: T;
  locationLine2?: T;
  openingHoursTitle?: T;
  openingHours?:
    | T
    | {
        day?: T;
        hours?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  phoneLabel?: T;
  phone?: T;
  emailLabel?: T;
  email?: T;
  whatsappLabel?: T;
  whatsappNumber?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-page_select".
 */
export interface SupportPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  phoneLabel?: T;
  phone?: T;
  emailLabel?: T;
  email?: T;
  whatsappLabel?: T;
  whatsappNumber?: T;
  whatsappPrefillMessage?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkout-settings_select".
 */
export interface CheckoutSettingsSelect<T extends boolean = true> {
  deliveryPrice?: T;
  minimumDeliveryOrderAmount?: T;
  addressDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-pickup-configuration_select".
 */
export interface DeliveryPickupConfigurationSelect<T extends boolean = true> {
  monday?: T;
  tuesday?: T;
  wednesday?: T;
  thursday?: T;
  friday?: T;
  saturday?: T;
  sunday?: T;
  weekOverrides?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail-settings_select".
 */
export interface MailSettingsSelect<T extends boolean = true> {
  orderPlaced?:
    | T
    | {
        subject?: T;
        body?: T;
      };
  orderCancelled?:
    | T
    | {
        subject?: T;
        body?: T;
      };
  orderDelivered?:
    | T
    | {
        subject?: T;
        body?: T;
      };
  orderPickedUp?:
    | T
    | {
        subject?: T;
        body?: T;
      };
  boxAvailable?:
    | T
    | {
        subject?: T;
        body?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}